# Generated by Django 3.0.6 on 2020-06-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electro_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='electro_social.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, to='electro_social.UserInfo'),
        ),
    ]
